### PR TITLE
Correct way to update skins.json

### PR DESCRIPTION
**Pull request by draivin**

### CODE REVIEW

**Comment by TiagoGoddard** [comment]
Thank you!

**Comment by philippeop** [comment]
If I use the `parent.FC` data as-is and put it in `skins.json`, I get errors; it tries to find `mtypes` that appear in G.monsters that are not defined in skins.

**Comment by TiagoGoddard** [comment]
Maybe our skins are old?

Em 27 de dez de 2016 11:01, "philippeop" <notifications@github.com>
escreveu:

**Comment by philippeop** [comment]
I'm checking this with the game itself;
```
Object.keys(G.monsters).filter(m => Object.keys(parent.FC).indexOf(m) < 0)
=
["eelemental", "jrat", "welemental", "felemental", "nelemental"]
```

Those 5 monsters don't exist in `parent.FC`. 

But I just checked the old method and they didn't exist in the `returnSkin` object either. So doesn't matter much. So `show_json(parent.FC)` works as well.

**Comment by philippeop** [comment]
I've added a anti-500ISE check to the sprite code in 07331553c340ae367e41d617fb0b7193a49f7f04 to prevent fatal errors when we will start using the `parent.FC` data

**Pull request merged**
